function support_SaveBaselineValuesEveryTrial(BaselineValuesEveryTrial, Config, Meta, Participants)
    
    col_Participants = transpose([{ [Meta.CfPrefix '_' 'Participant'] }  Participants]);
    cols_sub_vals = cell(length(Participants)+1, size(BaselineValuesEveryTrial,2));
    cols_sub_vals(1, 1:size(BaselineValuesEveryTrial,2)) = num2cell(1:size(BaselineValuesEveryTrial,2));
    cols_sub_vals(2:length(Participants)+1, :) = num2cell(BaselineValuesEveryTrial);
    outputMatrix = [col_Participants cols_sub_vals];

    % hack to force Matlab output numbers instead of scientific notation
    outputMatrix(cellfun(@isnumeric,outputMatrix)) = compose('%.10f', [outputMatrix{cellfun(@isnumeric,outputMatrix)}]);

    OutFilePath = char([ ...
        '~RESULTS/' Meta.RootDirTag '/' ...
        'TEPR csv' ...
        ' alignSR=' num2str(Config.AlignToStimOrResp) ...
        ' filt=' num2str(Config.Filter.Behav.Enabled) ...
        ' (' Config.Filter.Behav.FriendlyName ')'...
        '/']);
    
    if ~exist(OutFilePath, 'dir')
        mkdir(OutFilePath);
    end

    OutFileName = char([ ...
        'PD_Baseline-values every trial' ...
        ' BL=[' num2str(Config.BaselineFromSec) ' ' num2str(Config.BaselineToSec) ']' ...
        ' alignSR=' num2str(Config.AlignToStimOrResp) ...
        ' filt=' num2str(Config.Filter.Behav.Enabled) ' (' Config.Filter.Behav.FriendlyName ')' ...
        ]);

%     OutFileName = [ Meta.CfPrefix '_' 'PD_Baseline-values' ' BLfromSec=' num2str(Config.BaselineFromSec) '; BLtoSec=' num2str(Config.BaselineToSec) ' Config.AlignToStimOrResp=' num2str(Config.AlignToStimOrResp) ' filt=' num2str(Config.Filter.Behav.Enabled) ' (' Config.Filter.Behav.FriendlyName ')' ];

    writecell(outputMatrix,[OutFilePath OutFileName '.csv'],'Delimiter',';'); % writematrix nem jĂł cell mĂˇtrixra

end