function support_SavePeakValues(PeakValues, Config, Meta, Participants)

    col_Participants = transpose([{ [Meta.CfPrefix '_' 'Participant'] }  Participants]);
    cols_sub_vals = cell(length(Participants)+1, 1);
    cols_sub_vals(1, 1) = { [Meta.CfPrefix '_' 'Filtered-PD']};
    cols_sub_vals(2:length(Participants)+1, 1) = num2cell(PeakValues);
    outputMatrix = [col_Participants cols_sub_vals];
    
    OutFilePath = char([ ...
        '~RESULTS/' Meta.RootDirTag '/' ...
        'TEPR csv' ...
        ' alignSR=' num2str(Config.AlignToStimOrResp) ...
        ' filt=' num2str(Config.Filter.Behav.Enabled) ...
        ' (' Config.Filter.Behav.FriendlyName ')'...
        '/']);
    
    if ~exist(OutFilePath, 'dir')
        mkdir(OutFilePath);
    end
    
    OutFileName = char([ ...
        'Peaks' ...
        ' P=[' num2str(Config.PeakFromSec) ' ' num2str(Config.PeakToSec) ']' ...
        ' BL=[' num2str(Config.BaselineFromSec) ' ' num2str(Config.BaselineToSec) ']' ...
        ' alignSR=' num2str(Config.AlignToStimOrResp) ...
        ' filt=' num2str(Config.Filter.Behav.Enabled) ' (' Config.Filter.Behav.FriendlyName ')' ...
        ]);
    
    %     OutFilePath = ['~RESULTS/' Meta.RootDirTag '/' 'TEPR csv' ' Config.AlignToStimOrResp=' num2str(Config.AlignToStimOrResp) ' filt=' num2str(Config.Filter.Behav.Enabled) ' (' Config.Filter.Behav.FriendlyName ')'  '/' ];
    % %     OutFilePath = ['~RESULTS/' Meta.RootDirTag '/' 'TEPR csv' '/' ];
    %     mkdir(OutFilePath);
    % OutFileName = [ 'peaks' ' PfromSec=' num2str(Config.PeakFromSec) '; PtoSec=' num2str(Config.PeakToSec) ' BLfromSec=' num2str(Config.BaselineFromSec) '; BLtoSec=' num2str(Config.BaselineToSec) ' alignSR=' num2str(Config.AlignToStimOrResp) ' filt=' num2str(Config.Filter.Behav.Enabled) ' (' Config.Filter.Behav.FriendlyName ')' ];
    
    writecell(outputMatrix,[OutFilePath OutFileName '.csv'],'Delimiter',';'); % writematrix nem jĂł cell mĂˇtrixra

end